### ISSUE TITLE
It chraches when I try to start it

### ISSUE THREAD

**Issue by sennecoolgames** [vopswtf/Vops-Capes#13]
/var/lib/pufferpanel/servers/10810ea0/api/storage/json.js:22
    return cb(`/assets/capes/${userData.users[username]?.cape || "If you are seeing this, update your node.js!"}.png`);
                                                                                         ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/lib/pufferpanel/servers/10810ea0/api/routes/capes.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
DAEMON Running post-execution steps

**Comment by vopswtf** [comment]
Please update your version of NodeJS as specified in the error.

Note that Ubuntu does NOT have LTS of NodeJS. For that, use [nvm](https://github.com/nvm-sh/nvm).
